// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicManager.Models;

#nullable disable

namespace MusicManager.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20220924221930_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MusicManager.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Fact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fact = "positive album",
                            Genre = "Alternative",
                            Label = "UME",
                            ReleaseDate = new DateTime(2015, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Higher Truth"
                        },
                        new
                        {
                            Id = 2,
                            Fact = "released after death",
                            Genre = "Alternative",
                            Label = "UME",
                            ReleaseDate = new DateTime(2020, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "No One Sings Like You Anymore, Vol. 1"
                        },
                        new
                        {
                            Id = 3,
                            Fact = "Second album by Mr. Bruce",
                            Genre = "Rock and Roll",
                            Label = "Columbia",
                            ReleaseDate = new DateTime(1973, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wild, the Innocent, & the E Street Shuffle"
                        },
                        new
                        {
                            Id = 4,
                            Fact = "Was supposed to have duets with Michael Jackson",
                            Genre = "Synth-Pop",
                            Label = "Columbia",
                            ReleaseDate = new DateTime(1985, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mr. Bad Guy"
                        },
                        new
                        {
                            Id = 5,
                            Fact = "First concept album",
                            Genre = "Country",
                            Label = "Columbia",
                            ReleaseDate = new DateTime(1960, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ride This Train"
                        },
                        new
                        {
                            Id = 6,
                            Fact = "About the american working man",
                            Genre = "Country",
                            Label = "Legacy",
                            ReleaseDate = new DateTime(1963, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blood, Sweat, and Tears"
                        },
                        new
                        {
                            Id = 7,
                            Fact = "Nasty cover photo",
                            Genre = "Alternative",
                            Label = "DreamWorks",
                            ReleaseDate = new DateTime(2000, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Infest"
                        },
                        new
                        {
                            Id = 8,
                            Fact = "Third album from the dude",
                            Genre = "Alternative",
                            Label = "Fueled by Ramen",
                            ReleaseDate = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Death of an Optimist"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Traditional Pop",
                            Label = "Columbia",
                            ReleaseDate = new DateTime(1946, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Voice of Frank Sinatra"
                        },
                        new
                        {
                            Id = 10,
                            Fact = "The thirteenth Beck album",
                            Genre = "Pop",
                            Label = "Capitol",
                            ReleaseDate = new DateTime(2017, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Colors"
                        },
                        new
                        {
                            Id = 11,
                            Fact = "Release date month and day is a little ambiguous",
                            Genre = "Country",
                            Label = "Columbia",
                            ReleaseDate = new DateTime(1974, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Five Feet High and Rising"
                        },
                        new
                        {
                            Id = 12,
                            Fact = "Like a satanic K-tel record thats been found in a trash dumpster",
                            Genre = "Alternative",
                            Label = "DGC",
                            ReleaseDate = new DateTime(1994, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mellow Gold"
                        });
                });

            modelBuilder.Entity("MusicManager.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1964, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Chris Cornell",
                            DeathDate = new DateTime(2017, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fact = "Lead Singer in Soundgarden",
                            Hometown = "Seattle"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1949, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Bruce Springsteen",
                            Fact = "Dedicated an album to 9/11 victims",
                            Hometown = "New Jersey"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1946, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Farrokh Bulsara",
                            DeathDate = new DateTime(1991, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fact = "Born in Zanzibar",
                            Hometown = "Sultanate",
                            StageName = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1932, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Johnny Cash",
                            DeathDate = new DateTime(2003, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fact = "Covered a Nine-Inch Nails Song",
                            Hometown = "Kingsland",
                            StageName = "The Man in Black"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1976, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Jacoby Shaddix",
                            Fact = "Host of Scarred",
                            Hometown = "Vacaville",
                            StageName = "Papa Roach"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1993, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Jordan Benjamin",
                            Fact = "Canadian dude",
                            Hometown = "Toronto",
                            StageName = "Grandson"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1915, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Frank Sinatra",
                            DeathDate = new DateTime(1998, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fact = "Lived in a rat-infested shed",
                            Hometown = "Hoboken"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1970, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Bek Cambell",
                            Fact = "Host of Scarred",
                            Hometown = "Los Angelas",
                            StageName = "Beck"
                        });
                });

            modelBuilder.Entity("MusicManager.Models.ArtistAlbum", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.HasKey("ArtistId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("ArtistAlbums");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            AlbumId = 1
                        },
                        new
                        {
                            ArtistId = 1,
                            AlbumId = 2
                        },
                        new
                        {
                            ArtistId = 2,
                            AlbumId = 3
                        },
                        new
                        {
                            ArtistId = 3,
                            AlbumId = 4
                        },
                        new
                        {
                            ArtistId = 4,
                            AlbumId = 5
                        },
                        new
                        {
                            ArtistId = 4,
                            AlbumId = 6
                        },
                        new
                        {
                            ArtistId = 5,
                            AlbumId = 7
                        },
                        new
                        {
                            ArtistId = 6,
                            AlbumId = 8
                        },
                        new
                        {
                            ArtistId = 7,
                            AlbumId = 9
                        },
                        new
                        {
                            ArtistId = 8,
                            AlbumId = 10
                        },
                        new
                        {
                            ArtistId = 4,
                            AlbumId = 11
                        },
                        new
                        {
                            ArtistId = 8,
                            AlbumId = 12
                        });
                });

            modelBuilder.Entity("MusicManager.Models.ArtistSong", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("ArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistSongs");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            SongId = 1
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 2
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 3
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 4
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 5
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 6
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 7
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 8
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 9
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 10
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 11
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 12
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 13
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 14
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 15
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 16
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 17
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 18
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 19
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 20
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 21
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 22
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 23
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 24
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 25
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 26
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 27
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 28
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 29
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 30
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 31
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 32
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 33
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 34
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 35
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 36
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 37
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 38
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 39
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 40
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 41
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 42
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 43
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 44
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 45
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 46
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 47
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 48
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 49
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 50
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 51
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 52
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 53
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 54
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 55
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 56
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 57
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 58
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 59
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 60
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 61
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 62
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 63
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 64
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 65
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 66
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 67
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 68
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 69
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 70
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 71
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 72
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 73
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 74
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 75
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 76
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 77
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 78
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 79
                        },
                        new
                        {
                            ArtistId = 6,
                            SongId = 80
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 81
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 82
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 83
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 84
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 85
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 86
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 87
                        },
                        new
                        {
                            ArtistId = 7,
                            SongId = 88
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 89
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 90
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 91
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 92
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 93
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 94
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 95
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 96
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 97
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 98
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 99
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 100
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 101
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 102
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 103
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 104
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 105
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 106
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 107
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 108
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 109
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 110
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 111
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 112
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 113
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 114
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 115
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 116
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 117
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 118
                        },
                        new
                        {
                            ArtistId = 8,
                            SongId = 119
                        });
                });

            modelBuilder.Entity("MusicManager.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BillBoardDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BillBoardRank")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Length")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            BillBoardDate = new DateTime(2015, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 18,
                            Comment = "Good Song",
                            Length = new TimeSpan(0, 0, 3, 54, 0),
                            Name = "Nearly Forgot My Broken Heart",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 54, 0),
                            Name = "Dead Wishes",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 4, 32, 0),
                            Name = "Worried Moon",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 51, 0),
                            Name = "Before We Disappear",
                            Writer = ""
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 4, 41, 0),
                            Name = "Through the Window",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 38, 0),
                            Name = "Josephine",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 42, 0),
                            Name = "Murderer of Blue Skies",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 5, 6, 0),
                            Name = "Higher Truth",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 42, 0),
                            Name = "Let Your Eyes Wander",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 29, 0),
                            Name = "Only These Words",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 28, 0),
                            Name = "Circling",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 1,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 4, 19, 0),
                            Name = "Our Time in the Universe",
                            Writer = "Chris Cornell"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 22, 0),
                            Name = "Get It While You Can",
                            Writer = "Jerry Ragovoy"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 35, 0),
                            Name = "Jump into the Fire",
                            Writer = "Harry Nilsson"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 49, 0),
                            Name = "Sad Sad City",
                            Writer = "Aaron Behrens"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 2,
                            BillBoardDate = new DateTime(2020, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 25,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 4, 13, 0),
                            Name = "Patience",
                            Writer = "Guns N Roses"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 4, 12, 0),
                            Name = "Nothing Compares 2 U",
                            Writer = "Prince"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 14, 0),
                            Name = "Watching the Wheels",
                            Writer = "John Lennon"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 4, 0),
                            Name = "You Dont Know Nothing About Love",
                            Writer = "Jerry Ragovoy"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 23, 0),
                            Name = "Showdown",
                            Writer = "Jeff Lynne"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 3, 14, 0),
                            Name = "To Be Treated Rite",
                            Writer = "Terry Reid"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 2,
                            Comment = "Havent Heard",
                            Length = new TimeSpan(0, 0, 4, 15, 0),
                            Name = "Stay with Me Baby",
                            Writer = "Jerry Ragovoy"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 4, 31, 0),
                            Name = "The E Street Shuffle",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 5, 36, 0),
                            Name = "4th of July, Asbury Park(Sandy)",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 7, 9, 0),
                            Name = "Kittys Back",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 4, 47, 0),
                            Name = "Wild Billys Circus Story",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 7, 45, 0),
                            Name = "Incident on 57th Street",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 7, 4, 0),
                            Name = "Rosalita (Come Out Tonight)",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 3,
                            Length = new TimeSpan(0, 0, 9, 55, 0),
                            Name = "New York City Seranade",
                            Writer = "Bruce Springsteen"
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 42, 0),
                            Name = "Lets Turn It On",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 4, 5, 0),
                            Name = "Made in Heaven",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 38, 0),
                            Name = "I Was Born to Love You",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 29, 0),
                            Name = "Foolin Around",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 32, 0),
                            Name = "Your Kind of Lover",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 4,
                            BillBoardDate = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 159,
                            Length = new TimeSpan(0, 0, 4, 9, 0),
                            Name = "Mr. Bad Guy",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 4, 8, 0),
                            Name = "Man Made Paradise",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 0, 0),
                            Name = "There Must Be More to Life Than This",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 42, 0),
                            Name = "My Love is Dangerous",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 46, 0),
                            Name = "Love Me Like Theres No Tomorrow",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 4,
                            Length = new TimeSpan(0, 0, 3, 42, 0),
                            Name = "Living on My Own",
                            Writer = "Freddie Mercury"
                        },
                        new
                        {
                            Id = 41,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 4, 58, 0),
                            Name = "Loading Coal",
                            Writer = "Merle Travis"
                        },
                        new
                        {
                            Id = 42,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 4, 12, 0),
                            Name = "Slow Rider",
                            Writer = "Johnny Cash"
                        },
                        new
                        {
                            Id = 43,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 3, 2, 0),
                            Name = "Lumberjack",
                            Writer = "Leon Payne"
                        },
                        new
                        {
                            Id = 44,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 4, 47, 0),
                            Name = "Dorraine of Ponchartrain",
                            Writer = "Cash"
                        },
                        new
                        {
                            Id = 45,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 4, 26, 0),
                            Name = "Going to Memphis",
                            Writer = "Hollie Dew"
                        },
                        new
                        {
                            Id = 46,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 2, 55, 0),
                            Name = "When Papa Played the Dobro",
                            Writer = "Cash"
                        },
                        new
                        {
                            Id = 47,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 3, 50, 0),
                            Name = "Boss Jack",
                            Writer = "Tex Ritter"
                        },
                        new
                        {
                            Id = 48,
                            AlbumId = 5,
                            Length = new TimeSpan(0, 0, 4, 10, 0),
                            Name = "Old Doc Brown",
                            Writer = "Red Foley"
                        },
                        new
                        {
                            Id = 49,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 9, 3, 0),
                            Name = "The Legend of John Henrys Hammer",
                            Writer = "Johnny Cash"
                        },
                        new
                        {
                            Id = 50,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 3, 3, 0),
                            Name = "Tell Him Im Gone",
                            Writer = "Cash"
                        },
                        new
                        {
                            Id = 51,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 2, 35, 0),
                            Name = "Another Man Done Gone",
                            Writer = "Vera Hall"
                        },
                        new
                        {
                            Id = 52,
                            AlbumId = 6,
                            BillBoardDate = new DateTime(1963, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 13,
                            Length = new TimeSpan(0, 0, 2, 17, 0),
                            Name = "Busted",
                            Writer = "Harlan Howard"
                        },
                        new
                        {
                            Id = 53,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 3, 2, 0),
                            Name = "Casey Jones",
                            Writer = "Cash"
                        },
                        new
                        {
                            Id = 54,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 3, 15, 0),
                            Name = "Nine Pound Hammer",
                            Writer = "Merle Travis"
                        },
                        new
                        {
                            Id = 55,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 2, 40, 0),
                            Name = "Chain Gang",
                            Writer = "Howard"
                        },
                        new
                        {
                            Id = 56,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 2, 6, 0),
                            Name = "Waiting for a Train",
                            Writer = "Jimmie Rogers"
                        },
                        new
                        {
                            Id = 57,
                            AlbumId = 6,
                            Length = new TimeSpan(0, 0, 2, 11, 0),
                            Name = "Roughneck",
                            Writer = "Sheb Wooley"
                        },
                        new
                        {
                            Id = 58,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 4, 9, 0),
                            Name = "Infest",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 59,
                            AlbumId = 7,
                            BillBoardDate = new DateTime(2000, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 1,
                            Length = new TimeSpan(0, 0, 3, 19, 0),
                            Name = "Last Resort",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 60,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 41, 0),
                            Name = "Broken Home",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 61,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 6, 0),
                            Name = "Dead Cell",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 62,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 54, 0),
                            Name = "Between Angels and Insects",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 63,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 34, 0),
                            Name = "Blood Brothers",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 64,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 42, 0),
                            Name = "Revenge",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 65,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 29, 0),
                            Name = "Snakes",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 66,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 35, 0),
                            Name = "Never Enough",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 67,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 3, 47, 0),
                            Name = "Binge",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 68,
                            AlbumId = 7,
                            Length = new TimeSpan(0, 0, 9, 36, 0),
                            Name = "Thrown Away",
                            Writer = "Papa Roach"
                        },
                        new
                        {
                            Id = 69,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 2, 31, 0),
                            Name = "Death of an Optimist // Intro",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 70,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 18, 0),
                            Name = "In Over My Head",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 71,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 36, 0),
                            Name = "Identity",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 72,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 25, 0),
                            Name = "Left Behind",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 73,
                            AlbumId = 8,
                            BillBoardDate = new DateTime(2021, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 10,
                            Length = new TimeSpan(0, 0, 3, 28, 0),
                            Name = "Dirty",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 74,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 2, 22, 0),
                            Name = "The Ballad of G and X // Interlude",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 75,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 2, 49, 0),
                            Name = "We Did It!!!",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 76,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 22, 0),
                            Name = "WWIII",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 77,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 12, 0),
                            Name = "Riptide",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 78,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 17, 0),
                            Name = "Pain Shopping",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 79,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 9, 0),
                            Name = "Drop Dead",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 80,
                            AlbumId = 8,
                            Length = new TimeSpan(0, 0, 3, 31, 0),
                            Name = "Welcome to Paradise // Outro",
                            Writer = "Grandson"
                        },
                        new
                        {
                            Id = 81,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 3, 0, 0),
                            Name = "You Go to My Head",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 82,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 3, 18, 0),
                            Name = "Someone to Watch Over Me",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 83,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 3, 8, 0),
                            Name = "These Foolish Things",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 84,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 2, 53, 0),
                            Name = "Why Shouldnt I?",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 85,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 2, 46, 0),
                            Name = "I Dont Know Why",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 86,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 3, 8, 0),
                            Name = "Try a Little Tenderness",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 87,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 3, 11, 0),
                            Name = "I Dont Stand a Ghost of a Chance with You",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 88,
                            AlbumId = 9,
                            Length = new TimeSpan(0, 0, 2, 37, 0),
                            Name = "Paradise",
                            Writer = "Axel Stordahl"
                        },
                        new
                        {
                            Id = 89,
                            AlbumId = 10,
                            BillBoardDate = new DateTime(2018, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 3,
                            Length = new TimeSpan(0, 0, 4, 21, 0),
                            Name = "Colors",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 90,
                            AlbumId = 10,
                            Length = new TimeSpan(0, 0, 5, 0, 0),
                            Name = "Seventh Heaven",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 91,
                            AlbumId = 10,
                            Length = new TimeSpan(0, 0, 4, 7, 0),
                            Name = "Im So Free",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 92,
                            AlbumId = 10,
                            Length = new TimeSpan(0, 0, 3, 44, 0),
                            Name = "Dear Life",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 93,
                            AlbumId = 10,
                            Length = new TimeSpan(0, 0, 4, 32, 0),
                            Name = "No Distraction",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 94,
                            AlbumId = 10,
                            BillBoardDate = new DateTime(2015, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 1,
                            Length = new TimeSpan(0, 0, 4, 57, 0),
                            Name = "Dreams",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 95,
                            AlbumId = 10,
                            BillBoardDate = new DateTime(2016, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 10,
                            Length = new TimeSpan(0, 0, 3, 40, 0),
                            Name = "Wow",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 96,
                            AlbumId = 10,
                            BillBoardDate = new DateTime(2018, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 30,
                            Length = new TimeSpan(0, 0, 3, 10, 0),
                            Name = "Up All Night",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 97,
                            AlbumId = 10,
                            Length = new TimeSpan(0, 2, 55, 0, 0),
                            Name = "Square One",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 98,
                            AlbumId = 10,
                            Length = new TimeSpan(0, 0, 3, 13, 0),
                            Name = "Fix Me",
                            Writer = "Beck Hansen"
                        },
                        new
                        {
                            Id = 99,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 33, 0),
                            Name = "In Them Old Cottonfields Back Home",
                            Writer = "Lead Belly"
                        },
                        new
                        {
                            Id = 100,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 38, 0),
                            Name = "Im So Lonesome I Could Cry",
                            Writer = "Hank Williams"
                        },
                        new
                        {
                            Id = 101,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 17, 0),
                            Name = "Frankies Man Johnny",
                            Writer = "Johnny Cash"
                        },
                        new
                        {
                            Id = 102,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 22, 0),
                            Name = "In the Jailhouse Now",
                            Writer = "Jimmie Rodgers"
                        },
                        new
                        {
                            Id = 103,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 23, 0),
                            Name = "My Shoes Keep Walking Back to You",
                            Writer = "Lee Ross"
                        },
                        new
                        {
                            Id = 104,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 3, 4, 0),
                            Name = "Dont Take Your Guns to Town",
                            Writer = "Cash"
                        },
                        new
                        {
                            Id = 105,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 4, 0),
                            Name = "Great Speckled Bird",
                            Writer = "Roy Carter"
                        },
                        new
                        {
                            Id = 106,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 1, 49, 0),
                            Name = "Five Feet High and Rising",
                            Writer = "Cash "
                        },
                        new
                        {
                            Id = 107,
                            AlbumId = 11,
                            Length = new TimeSpan(0, 0, 2, 29, 0),
                            Name = "I Forgot More Than Youll Ever Know",
                            Writer = "Cecil. A Null"
                        },
                        new
                        {
                            Id = 108,
                            AlbumId = 12,
                            BillBoardDate = new DateTime(1994, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BillBoardRank = 1,
                            Length = new TimeSpan(0, 0, 3, 55, 0),
                            Name = "Loser",
                            Writer = "Hansen"
                        },
                        new
                        {
                            Id = 109,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 3, 15, 0),
                            Name = "Pay No Mind(Snoozer)",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 110,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 3, 41, 0),
                            Name = "F*cking with My Head(Mountain Dew Rock)",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 111,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 3, 28, 0),
                            Name = "Whickeyclone, Hotel City 1997",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 112,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 3, 57, 0),
                            Name = "Soul Sucking Jerk",
                            Writer = "Hansen"
                        },
                        new
                        {
                            Id = 113,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 2, 55, 0),
                            Name = "Truckdrivin Neighbors Downstairs(Yellow Sweat)",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 114,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 4, 14, 0, 0),
                            Name = "Sweet Sunshine",
                            Writer = "Hansen"
                        },
                        new
                        {
                            Id = 115,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 4, 0, 0),
                            Name = "Beercan",
                            Writer = "Hansen"
                        },
                        new
                        {
                            Id = 116,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 5, 34, 0),
                            Name = "Steal My Body Home",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 117,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 2, 55, 0),
                            Name = "Nitemare Hippy Girl",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 118,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 2, 4, 0),
                            Name = "Mutherf*ker",
                            Writer = "Beck"
                        },
                        new
                        {
                            Id = 119,
                            AlbumId = 12,
                            Length = new TimeSpan(0, 0, 2, 4, 0),
                            Name = "Blackhole",
                            Writer = "Beck"
                        });
                });

            modelBuilder.Entity("MusicManager.Models.ArtistAlbum", b =>
                {
                    b.HasOne("MusicManager.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicManager.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicManager.Models.ArtistSong", b =>
                {
                    b.HasOne("MusicManager.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicManager.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicManager.Models.Song", b =>
                {
                    b.HasOne("MusicManager.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.Navigation("Album");
                });
#pragma warning restore 612, 618
        }
    }
}
